LearnsMate/LearnsMateFrontend

- src/views/MemberView.vue
- 제목 : feat(issue 번호): 기능명 ✨ 기능 추가/수정: MemberView index 수정
<br/>
인덱스와 마진 수정해서 css 맞췄습니다.
<br/>
<br/>
<br/>
> ✨ 기능 추가/수정: MemberView index 수정

- src/assets/css/style.css
- src/components/AppHeader.vue
- src/components/sideMenu/MarketingSideMenu.vue
- src/views/MarketingView.vue
- 제목 : feat(#6 ):  MarketingView 글목록 추가
<br/>
- MarketingView 글목록 추가
<br/>
<br/>
- 상단 필터링 만들기
<br/>
> ✨ 기능 추가: MarketingView 글목록 추가

- src/components/member/MemberFilter.vue
- src/components/sideMenu/MemberSideMenu.vue
- src/views/MemberView.vue
- 제목 : feat(#12 ): 기능명 ✨기능 추가/수정: Member 전체 조회, 페이지네이션, 상세창 추가
<br/>
Member 전체 조회
페이지네이션 적용
상세창 추가
filter css 수정
<br/>
<br/>
백이랑 연동 후 데이터 채워넣기
<br/>
> ✨기능 추가/수정: Member 전체 조회, 페이지네이션, 상세창 추가

- src/components/member/BlacklistFilter.vue
- src/components/member/MemberFilter.vue
- src/views/member/StudentBlacklistView.vue
- 제목 : feat(#16 ): 기능명 ✨기능 추가/수정: StudentBlacklist, View css 수정
<br/>
✨기능 추가/수정: StudentBlacklist, View css 수정
<br/>
> ✨기능 추가/수정: StudentBlacklist, View css 수정

- src/views/VocView.vue
voc 관련 api 데이터 반환형 수정 포맷 수정했습니다.
> voc 관련 api 데이터 반환형 수정

- src/components/AppHeader.vue
- src/components/member/ReservedBlacklist.vue
- src/views/member/StudentBlacklistView.vue
- src/views/member/StudentView.vue
- src/views/member/TutorBlacklistView.vue
- src/views/member/TutorView.vue
- 제목 : feat(#64 ): 기능명 ✨기능 추가: 학생 상세보기 추가/수정
<br/>
예비 블랙리스트 추가하고 예비 블랙리스트도 켜지게 했습니다.
계속해서 CSS 수정
<br/>
연동 및 학생 상세조회
<br/>
> ✨기능 추가: 학생 상세보기 추가/수정

- src/views/member/StudentView.vue
- src/views/member/TutorView.vue
✨기능 추가: TutorView 페이지네이션, 필터링 수정
<br/>
✨기능 추가: TutorView 페이지네이션, 필터링 수정
<br/>
<br/>
피니아
<br/>
> ✨기능 추가: TutorView 페이지네이션, 필터링 수정

- src/assets/css/voc/VOCView.css
- src/components/voc/VOCFilter.vue
- src/views/voc/VocView.vue
<br/>
VOC 메인 화면 DML 구문 이후 페이지네이션까지 구현 완료. api 테스트 완료했습니다.
<br/>
<br/>
<br/>
> VOC 메인 화면 DML 구문 이후 페이지네이션까지 구현 완료. api 테스트 완료

- package-lock.json
- package.json
- src/components/login/LoginLeft.vue
- src/main.js
- src/stores/loginState.js
- src/views/MainView.vue
- 제목 : feat: ✨ 기능 추가: 로그인 토큰 데이터 연결 기능 추가
<br/>
- 로그인 토큰 데이터 연결 기능 추가하였습니다.
<br/>
<br/>
- Http only 쿠키로 토큰 담아보기 
<br/>
> ✨ 기능 추가: 로그인 토큰 데이터 연결 기능 추가

- package-lock.json
- package.json
- src/views/voc/VocView.vue
<br/>
VOC 액셀 다운로드 기능 추가했습니다.
<br/>
> ✨ 기능 추가 : VOC 액셀 다운로드 기능 추가

- src/assets/css/voc/VOCView.css
- src/views/voc/VocView.vue
<br/>
VOC 액셀 다운로드 기능 추가
board-row 한 화면에 50개로 개수 증가, 한 화면에 보이는 데이터의 개수는 15개지만 스크롤 추가로 50개까지 확인 가능
<br/>
> VOC 액셀 다운로드 기능 추가 및 board-row 개수 증가 및 스크롤 추가

- src/assets/css/voc/VOCView.css
- src/components/modules/VOCEditModule.vue
- src/views/voc/VocView.vue
<br/>
VOC 전체 조회, 단 건 조회, VOC 답변 등록, 수정 기능 구현해서 완료했습니다.
> VOC 전체 조회, 단 건 조회, VOC 답변 등록, 수정 기능 구현

- src/assets/css/lecture/LectureView.css
- src/components/lecture/LectureFilter.vue
- src/views/lecture/LectureView.vue
<br/>
lecture offset 페이지네이션으로 변경 및 필터링 기능 수정수정했습니다.
커서 페이지네이션으로 구현했을 때의 문제점을 해결했고, 추후 보완하겠습니다.
<br/>
> lecture offset 페이지네이션으로 변경 및 필터링 기능 수정

- src/assets/css/member/StudentView.css
- src/views/member/BlacklistView.vue
- src/views/member/StudentView.vue
<br/>
회원 상세조회
<br/>
<br/>
상세조회 강의추천 추가
<br/>
> ✨기능 추가: 학생 상세조회 데이터 조회 추가

- src/views/marketing/campaign/CampaignRegisterPage.vue
- 제목 : feat(#83 ): formatDateFromArray 제거
<br/>
<br/>
<br/>
<br/>
> formatDateFromArray 제거

- src/assets/css/lecture/LectureView.css
- src/components/lecture/MonthlyLectureModal.vue
- src/views/lecture/LectureView.vue
<br/>
lecture 월별 데이터 그래프 추가 + 필터링 추가, 단 건 조회 시 클릭 -> 구매 전환율 그래프 추가 + 필터링 추가/수정했습니다.
<br/>
> lecture 월별 데이터 그래프 추가 + 필터링 추가, 단 건 조회 시 클릭 -> 구매 전환율 그래프 추가 + 필터링 추가

- src/components/marketing/TargetUserSelectModal.vue
- src/views/marketing/campaign/AllCampaignsGetPage.vue
- src/views/marketing/campaign/CampaignGetPage.vue
- src/views/marketing/campaign/CampaignRegisterPage.vue
- 제목 : feat(#100 , #101, #83 ): 뒤로가기 버튼 추가
<br/>
- 캠페인 단건 조회 하단에 뒤로가기 버튼 추가
- 예약발송이더라도 이미 보내진 캠페인이라면 수정/취소 불가능하게 처리
- 예약 시간 선택할 때 현재시간 이전은 선택 못하게 처리
- 타겟유저 페이징 처리
- 타겟유저 필터링 코드 수정하기 -> 카멜케이스 처리한게 문제였음
<br/>
<br/>
- 캠페인 템플릿 api 연결 / 엑셀
<br/>
> ♻️코드 수정: 뒤로가기 버튼 추가

- src/assets/css/member/StudentView.css
- src/plugins/axios.js
- src/views/member/StudentView.vue
- src/views/member/TutorView.vue
<br/>
엑셀 다운로드 기능 구현
custom axios interceptor 수정 -> 엑셀 요청시 메서드 적용 안되게 수정
<br/>
블랙리스트 엑셀 다운, 업로드
<br/>
> ✨기능 추가: 회원 엑셀 다운로드 기능 구현

- src/views/member/BlacklistView.vue
- src/views/member/StudentView.vue
<br/>
✨기능 추가: 블랙리스트 엑셀 다운로드, 회원 엑셀 업로드 추가
<br/>
데이터 분석
<br/>
> ✨기능 추가: 블랙리스트 엑셀 다운로드, 회원 엑셀 업로드 추가

- src/components/member/StudentCategoryRatioModal.vue
- src/views/member/StudentView.vue
<br/>
✨기능 추가: 학생 카테고리 비율 chart 추가
<br/>
<br/>
회원 로그인 회원가입 서비스 구현
<br/>
> ✨기능 추가: 학생 카테고리 비율 chart 추가

- src/components/marketing/TargetUserSelectModal.vue
- src/views/marketing/campaign/AllCampaignsGetPage.vue
- src/views/marketing/campaign/CampaignRegisterPage.vue
- 제목 : feat(#107  #106 ): 엑셀 업로드 추가
<br/>
- 캠페인 엑셀 다운로드 기능 추가
- 캠페인 타겟 유저 엑셀 업로드 기능 추가
<br/>
<br/>
- 쿠폰 엑셀 업로드
<br/>
> ✨기능 추가: 엑셀 업로드 추가

- src/components/marketing/CampaignCouponSelectFilter.vue
- src/components/marketing/CampaignTemplateGetModal.vue
- src/views/marketing/campaignTemplate/AllCampaignTemplatesGetPage.vue
- 제목 : feat(issue 번호): 캠페인 단건 조회 추가
<br/>
- 캠페인 템플릿 전체 조회에서 템플릿 선택 시 단건 조회가 가능합니다.
<br/>
<br/>
- 캠페인 템플릿 수정, 삭제
<br/>
> ✨기능 추가: 캠페인 단건 조회 추가

- src/components/marketing/CampaignTemplateGetModal.vue
- src/views/marketing/campaignTemplate/AllCampaignTemplatesGetPage.vue
- 제목 : feat(#118 ): 캠페인 템플릿 수정
<br/>
- 캠페인 템플릿 단건 조회 시 수정버튼을 누르면 캠페인 템플릿을 수정할 수 있습니다.
<br/>
<br/>
- 캠페인 템플릿 삭제 
<br/>
> ✨기능 추가: 캠페인 템플릿 수정

- src/components/marketing/CampaignTemplateGetModal.vue
- src/components/modules/ConfirmModule.vue
- src/components/modules/DeleteModule.vue
- 제목 : feat(#120 ): 캠페인 템플릿 삭제
<br/>
- 캠페인 템플릿 삭제 기능
<br/>
<br/>
- 
<br/>
> ✨기능 추가: 캠페인 템플릿 삭제

- src/components/login/LoginLeft.vue
- src/stores/loginState.js
- src/views/MainView.vue
- 제목 : feat(#38 ): ✨ 기능 추가: 직원 로그인시 토큰 쿠키에 담는 기능 추가
-
<br/>
페이지 전환시 토큰을 들고 다닐 수 있게 -> Pinia에서 상태 관리 -> 
fetchLoginState 액션이 /admin/status 요청으로 토큰 기반 인증을 확인.
인증 성공 시 사용자 이름과 권한을 상태에 저장.
<br/>
<br/>
- 로그아웃 구현하기
<br/>
> ✨ 기능 추가: 직원 로그인시 토큰 쿠키에 담는 기능 추가

- src/components/AppHeader.vue
- src/stores/loginState.js
- 제목 : feat: ✨ 기능 추가: 직원 로그아웃 api 호출 기능 추가
<br/>
직원 로그아웃 api 호출 기능 추가
<br/>
<br/>
- 비밀번호 이메일 인증 재설정 구현하기
<br/>
> ✨ 기능 추가: 직원 로그아웃 api 호출 기능 추가

- src/composables/useActivityMonitor.js
- src/views/client/clientlecture/ClientCouponAddView.vue
- src/views/client/clientlecture/ClientLectureCart.vue
- src/views/client/clientlecture/ClientLectureDetail.vue
- src/views/client/clientlecture/ClientLectureView.vue
- src/views/client/clientlecture/ClientMyLectureView.vue
- src/views/client/clientmain/ClientMainView.vue
- src/views/client/clientvoc/ClientVOCMyView.vue
- src/views/client/clientvoc/ClientVOCView.vue
<br/>
♻️코드 수정: 컴포넌트 위치 이동으로 인한 리팩토링
<br/>
> ♻️코드 수정: 컴포넌트 위치 이동으로 인한 리팩토링

- src/components/AppHeader.vue
- src/stores/loginState.js
- 제목 : feat ✨ 기능 추가: 로그인 직원 관련 사번 및 부서 정보 기능 추가
- 
<br/>
해당 로그인 직원 정보 기능 추가 
<br/>
<br/>
- 비밀번호 이메일 인증 재설정 구현하기
<br/>
> ✨ 기능 추가: 로그인 직원 관련 사번 및 부서 정보 기능 추가

- src/views/voc/VocView.vue
<br/>
voc 답변 등록 시 새로 고침 안 되는 것 수정했습니다.
<br/>
> voc 답변 등록 시 새로 고침 안 되는 것 해결

- src/assets/css/voc/VOCView.css
- src/components/AppHeader.vue
- src/views/MainView.vue
- 제목 : feat: ✨ 기능 추가: Main 페이지 뷰 기능 추가
<br/>
메인페이지 구현하였습니다.
<br/>
<br/>
- Main 페이지 데이터 추가하
<br/>
> ✨ 기능 추가: Main 페이지 뷰 기능 추가

- src/components/sideMenu/MarketingSideMenu.vue
- src/views/marketing/campaignTemplate/AllCampaignTemplatesGetPage.vue
- 제목 : feat(#137 ): 캠페인 템플릿 엑셀 파일 다운로드 추가
<br/>
- 엑셀 다운로드 버튼 클릭 시 캠페인 템플릿을 다운로드 받을 수 있습니다.
<br/>
<br/>
<br/>
> ✨기능 추가: 캠페인 템플릿 엑셀 파일 다운로드 추가

- src/assets/css/member/StudentView.css
- src/views/member/StudentView.vue
> ✨기능 추가: 필요컬럼 추가

- src/views/marketing/campaign/CampaignGetPage.vue
- src/views/marketing/campaignTemplate/AllCampaignTemplatesGetPage.vue
- 제목 : feat(issue 번호): import 수정
<br/>
<br/>
<br/>
<br/>
> ♻️코드 수정: import 수정

- src/views/member/StudentView.vue
<br/>
✨기능 추가: StudentView memberDomrantFlat -> memberDormantStatus
<br/>
> ✨기능 추가: StudentView memberDomrantFlat -> memberDormantStatus

- src/assets/css/member/StudentView.css
- src/assets/css/member/TutorView.css
- src/views/member/StudentView.vue
- src/views/member/TutorView.vue
<br/>
✨기능 추가: 회원 view, css 변경
-> thead -> div로 변경
<br/>
> ✨기능 추가: 회원 view, css 변경

- src/components/marketing/TargetUserSelectModal.vue
- src/components/marketing/campaignTemplateRegisterModal.vue
- src/components/marketing/couponSelectModal.vue
- src/views/marketing/campaign/AllCampaignsGetPage.vue
- src/views/marketing/campaign/CampaignGetPage.vue
- src/views/marketing/campaignTemplate/AllCampaignTemplatesGetPage.vue
- 제목 : feat(issue 번호): 모달 오류 수정, 쿠폰 전체 선택 추가, 캠페인 단건 조회 수정
<br/>
- 모달 오류 수정, 쿠폰 전체 선택 추가, 캠페인 단건 조회 수정
<br/>
<br/>
<br/>
> ♻️코드 수정: 모달 오류 수정

- src/components/marketing/TargetUserSelectModal.vue
- src/views/marketing/campaign/AllCampaignsGetPage.vue
- src/views/marketing/campaignTemplate/AllCampaignTemplatesGetPage.vue
- 제목 : feat(#147 #146 ): 컬럼 선택 기능 추가
<br/>
- 캠페인/캠페인템플릿 컬럼 선택 기능 추가
<br/>
<br/>
<br/>
> ✨기능 추가: 컬럼 선택 기능 추가

- src/views/coupon/CouponRegisterView.vue
<br/>
- 쿠폰 등록을 완료했을 때 모달창이 자동으로 닫히고 쿠폰 등록 처음 화면으로 돌아가도록 수정
<br/>
<br/>
- 쿠폰 수정
<br/>
> ✨기능 추가 : 쿠폰 등록 완료 후 모달창 닫히도록 수정

- src/components/login/LoginPwLeft.vue
- 제목 : feat :💄 UI/스타일 파일 추가: 새 비밀번호 입력 창 생길 시, 비율 변경 스타일 추가
<br/>
비밀번호 재생성 시,  이메일 인증 가능하고, 비밀번호 재설정 기능 추가
<br/>
<br/>
- 리프레시토큰도 레디스에 담기 
<br/>
> 💄 UI/스타일 파일 추가: 새 비밀번호 입력 창 생길 시, 비율 변경 스타일 추가

- src/components/login/LoginPwLeft.vue
- src/stores/loginState.js
- 제목 : feat: ✨ 기능 수정: 직원 이메일 및 비밀번호 변수 기능 수정
<br/>
-  기능 수정: 직원 이메일 및 비밀번호 변수 기능 수정
<br/>
<br/>
- 프론트 데이터 api 연동
- 
<br/>
> ✨ 기능 수정: 직원 이메일 및 비밀번호 변수 기능 수정

- src/components/marketing/CouponDetail.vue
- src/views/coupon/CouponRegisterView.vue
- src/views/coupon/CouponView.vue
<br/>
- 쿠폰 전체 조회 시 개수에 1000 단위 콤마 추가
- 쿠폰 전체 조회 화면에서 글자 넘치지 않도록 처리
- 강의 카테고리, 난이도 한글로 보이도록 처리
- 쿠폰 수정 시 db에 날짜 저장되도록 수정
<br/>
<br/>
- 프론트 css 수정
<br/>
> feat(#151, #152, #153) 강의 조회 화면 수정

- src/components/AppHeader.vue
- src/stores/loginState.js
<br/>
✨기능 추가: exp(만료시간) 추가
✨기능 추가: 로그인 만료시간 추가
<br/>
<br/>
캠페인 발송
<br/>
> ✨기능 추가: exp(만료시간) 추가

- src/views/coupon/CouponRegisterView.vue
- src/views/coupon/CouponView.vue
<br/>
- 전체 쿠폰 조회 페이지네이션 적용
- 쿠폰 필터링 조회 페이지네이션 적용
- 쿠폰 등록 화면 강의 조회 페이지네이션 적용
<br/>
<br/>
- css 수정
<br/>
> ✨기능 추가: 쿠폰 화면 페이지네이션 적용

- src/views/marketing/campaign/CampaignRegisterPage.vue
- 제목 : feat(issue 번호): 매개변수 오류 수정
<br/>
- 쿠폰 엑셀 업로드의 매개변수명을 타겟유저로 잘못 설정함
<br/>
<br/>
<br/>
> ♻️코드 수정: 매개변수 오류 수정

- src/views/marketing/campaign/CampaignRegisterPage.vue
- 제목 : feat(#164 ): 발송 수단 추가
<br/>
- 캠페인 등록시 이메일로 발송할지 문자로 발송할지 선택하는 버튼
<br/>
<br/>
<br/>
> ✨기능 추가: 발송 수단 추가

- src/components/marketing/CampaignFilter.vue
- src/components/marketing/CampaignTemplateFilter.vue
- src/views/marketing/campaign/AllCampaignsGetPage.vue
- src/views/marketing/campaign/CampaignGetPage.vue
- src/views/marketing/campaignTemplate/AllCampaignTemplatesGetPage.vue
- 제목 : feat(#166 ): css 수정
<br/>
-  css 수정
<br/>
<br/>
<br/>
> 💄코드 수정: css 수정

- src/assets/css/lecture/LectureView.css
- src/assets/css/member/BlacklistView.css
- src/assets/css/member/ReservedBlacklistView.css
- src/assets/css/member/StudentView.css
- src/assets/css/member/TutorView.css
- src/components/AppHeader.vue
- src/components/member/BlackReason.vue
- src/components/member/BlacklistFilter.vue
- src/components/member/MemberFilter.vue
- src/components/member/StudentCategoryRatioModal.vue
- src/views/marketing/campaign/AllCampaignsGetPage.vue
- src/views/marketing/campaignTemplate/AllCampaignTemplatesGetPage.vue
- src/views/member/BlacklistView.vue
- src/views/member/ReservedBlacklistView.vue
- src/views/member/StudentView.vue
- src/views/member/TutorView.vue
- 제목 : feat(issue 번호): 기능명
ex) feat(17): pull request template 작성
(확인 후 지워주세요)
<br/>
고객 전체적인 css 수정
<br/>
<br/>
- 전체적인 css 수정하기 
<br/>
> 💄 UI/스타일 파일 추가: 토글 스타일 추가

- src/router/router.js
- src/views/member/StudentView.vue
<br/>
✨기능 추가: 새로고침시 로그인 기능 유지되게 수정
<br/>
> ✨기능 추가: 새로고침시 로그인 기능 유지되게 수정

- src/views/MainView.vue
- src/views/marketing/campaign/AllCampaignsGetPage.vue
- src/views/marketing/campaignTemplate/AllCampaignTemplatesGetPage.vue
- 제목 : feat(#170 ): 메인 페이지 수정
<br/>
<br/>
<br/>
<br/>
> ♻️코드 수정: 메인 페이지 수정

- src/components/AppHeader.vue
- src/components/client/clientvoc/ClientVOCModal.vue
- src/stores/loginState.js
<br/>
✨기능 추가/수정: admin 로그인 수정
<br/>
> ✨기능 추가/수정: admin 로그인 수정t

- package-lock.json
- package.json
- src/components/main/CategoryBarChart.vue
- src/components/sideMenu/MarketingSideMenu.vue
- src/views/MainView.vue
- 제목 : feat(issue 번호): CategoryBarChart 추가
<br/>
<br/>
<br/>
<br/>
> ✨기능 추가: CategoryBarChart 추가

- src/views/MainView.vue
- 제목 : feat(issue 번호): 기능명
ex) feat(17): pull request template 작성
(확인 후 지워주세요)
<br/>
<br/>
<br/>
<br/>
> ♻️코드 수정: class명 변경

- src/views/member/StudentView.vue
- 제목 : feat(#179 )
<br/>
✨기능 추가: 학생이 수간중인 강의 개수 표시하는 로직 추가
<br/>
<br/>
강의 쿠폰 등록 로직 추가
<br/>
> ✨기능 추가: 학생이 수간중인 강의 개수 표시하는 로직 추가

- src/components/marketing/CouponFilter.vue
- src/views/coupon/CouponView.vue
<br/>
- 쿠폰 등록 유형 필터 조건 추가
<br/>
<br/>
- css 추가
<br/>
> ✨기능 추가/수정: 쿠폰 등록 유형 필터 추가

- src/components/marketing/IssuedCouponDetail.vue
- src/components/marketing/IssuedCouponFilter.vue
- src/views/coupon/IssuedCouponView.vue
- src/views/marketing/campaign/AllCampaignsGetPage.vue
- src/views/marketing/campaignTemplate/AllCampaignTemplatesGetPage.vue
- 제목 : feat(issue 번호): IssuedCoupon 수정
<br/>
<br/>
<br/>
<br/>
> ♻️코드 수정: IssuedCoupon 수정

- src/views/coupon/IssuedCouponView.vue
- src/views/marketing/campaign/AllCampaignsGetPage.vue
- 제목 : feat(#185 ): IssueCouponView 컬럼 선택 추가
<br/>
- 발급쿠폰 페이지에서 필요한 컬럼만 선택할 수 있습니다.
<br/>
<br/>
<br/>
> ✨기능 추가: IssueCouponView 컬럼 선택 추가

- src/components/client/clientlecture/ClientAddCouponModal.vue
- src/views/client/clientlecture/ClientCouponAddView.vue
- src/views/client/clientlecture/ClientLectureDetail.vue
- 제목 : feat(#187 #188 ): 
<br/>
✨기능 추가: 강사 강의, 쿠폰 조회 및 쿠폰 등록
<br/>
<br/>
마스킹
<br/>
> ✨기능 추가: 강사 강의, 쿠폰 조회 및 쿠폰 등록

- src/views/coupon/IssuedCouponView.vue
- 제목 : feat(#190 ): IssueCouponView 엑셀 다운로드 수정
<br/>
- 발급쿠폰 엑셀 다운로드 시 컬럼 선택이 되어있는 경우 선택된 컬럼의 데이터만 다운로드 되도록 수정
<br/>
<br/>
<br/>
> ♻️코드 수정: IssueCouponView 엑셀 다운로드 수정

- src/views/coupon/CouponRegisterView.vue
<br/>
- ♻️ 코드 수정 : 쿠폰 등록 시 강의 필터링 기능 추가
<br/>
<br/>
- css 통일
<br/>
> ♻️ 코드 수정 : 쿠폰 등록 시 강의 필터링 기능 추가

- src/components/marketing/CouponFilter.vue
<br/>
- 쿠폰 활성화 필터 적용 안되는 현상 수정
<br/>
<br/>
- css 수정
<br/>
> ♻️코드 수정: 쿠폰 활성화 필터 적용 안되는 현상 수정

- src/views/MainView.vue
- 제목 : feat(#170 ): MainView 수정
<br/>
- 유저 정보 마스킹 처리, 영어 -> 한글 변
<br/>
<br/>
- 캠페인 css 수정
<br/>
> ♻️코드 수정: MainView 수정

- src/components/marketing/CampaignCouponSelectFilter.vue
- src/components/marketing/IssuedCouponDetail.vue
- src/components/marketing/TargetUserFilter.vue
- src/components/marketing/TargetUserSelectModal.vue
- src/components/marketing/couponSelectModal.vue
- src/components/modules/DeleteModule.vue
- src/components/sideMenu/MarketingSideMenu.vue
- src/views/MainView.vue
- src/views/coupon/IssuedCouponView.vue
- src/views/marketing/campaign/AllCampaignsGetPage.vue
- src/views/marketing/campaign/CampaignGetPage.vue
- src/views/marketing/campaign/CampaignRegisterPage.vue
- 제목 : feat(#166 ): 전체적인 CSS 수정
<br/>
- CSS 수정
<br/>
<br/>
<br/>
> ♻️코드 수정: CampaignCouponSelectFilter 수정

- src/components/marketing/TargetUserFilter.vue
- 제목 : feat(): 디자인 수정
<br/>
- 타겟유저 필터링 정렬
<br/>
<br/>
<br/>
> ♻️코드 수정: 디자인 수정

- src/assets/css/member/BlacklistView.css
- src/assets/css/member/ReservedBlacklistView.css
- src/assets/css/member/StudentView.css
- src/assets/css/member/TutorView.css
- src/components/member/MemberFilter.vue
- src/views/member/BlacklistView.vue
- src/views/member/ReservedBlacklistView.vue
- src/views/member/StudentView.vue
- src/views/member/TutorView.vue
- 제목 : feat(#199 )
<br/>
✨♻️기능 추가/수정: 블랙리스트, 예비블랙리스트, 학생, 강사 CSS 및 로직 수정
- 학생, 강사 컨테이너 CSS 수정
- 강사 상세조회시 강의 목록 안뜨던 버그 수정
- 필요 컬럼 정렬 맞추
<br/>
<br/>
마스킹
<br/>
> ✨♻️기능 추가/수정: 블랙리스트, 예비블랙리스트, 학생, 강사 CSS 및 로직 수정

- src/views/MainView.vue
- 제목 : feat(#170 ): 마스킹처리
<br/>
-  MainView 강사 이름, 학생 이름 마스킹 처
<br/>
<br/>
<br/>
> ♻️코드 수정: MainView 마스킹 처리

- src/views/marketing/campaign/AllCampaignsGetPage.vue
- src/views/marketing/campaignTemplate/AllCampaignTemplatesGetPage.vue
- 제목 : feat(issue 번호): board-row padding 수정
<br/>
<br/>
<br/>
<br/>
> ♻️코드 수정: board-row padding 수정

- src/assets/css/style.css
- src/components/marketing/CouponDetail.vue
- src/components/marketing/CouponFilter.vue
- src/views/coupon/CouponView.vue
- src/views/member/StudentView.vue
<br/>
- 화면 디자인 다른 부분과 일치하도록 수정
- 쿠폰 수정 시 날짜 데이터 추가하지 않을 시 저장되지 않는 오류 수정
<br/>
<br/>
- css 통일
<br/>
> ♻️ 코드 수정: 화면 디자인 및 프론트 오류 수정

- src/assets/css/member/BlacklistView.css
- src/assets/css/member/ReservedBlacklistView.css
- src/assets/css/member/StudentView.css
- src/assets/css/member/TutorView.css
- src/views/member/BlacklistView.vue
- src/views/member/ReservedBlacklistView.vue
- src/views/member/StudentView.vue
- src/views/member/TutorView.vue
- 제목 : feat(#205 #206 )
<br/>
student, blakclist, reservedBlacklist css를 통일했습니다.
상세 조회 클릭시에 정렬이 맞지 않던 오류를 고쳤습니다.
student detail 조회시 voc, coupon 토글을 추가했습니다.
<br/>
발표자료 제작
<br/>
> ✨♻️ 기능 추가/수정: student, blacklist, reservedBlacklist css 수정 및 student view 토글 추가

- src/assets/css/member/BlacklistView.css
- src/components/marketing/CouponDetail.vue
- src/views/coupon/CouponView.vue
> ✨기능 추가/수정: css 수정

- src/components/sideMenu/MarketingSideMenu.vue
- src/views/coupon/CouponRegisterView.vue
<br/>
- ✨♻️기능 추가/수정: 쿠폰 라우팅 수정 및 사이드메뉴 css 수정
> ✨♻️기능 추가/수정: 쿠폰 라우팅 수정 및 사이드메뉴 css 수정

- src/stores/loginState.js
<br/>
계속 로그인이 필요 없는 url 에서 401 에러가 뜨는 것을 없애기 위해 수정했습니다.
<br/>
> ♻️ 코드 수정: loginState 예외인 url들 401 에러 예외를 위해 수정

- src/views/coupon/CouponView.vue
<br/>
- 기능에서 어떤 부분이 구현되었는지 설명해주세요.
조회 시 콘솔에 정보가 담기는 것은 지양하는게 좋을 것 같아 쿠폰 비활성 관련해서 코드 확인을 하며 삭제했습니다.
<br/>
> ♻️ 코드 수정: console.log 삭제

- src/views/lecture/LectureView.vue
<br/>
Lecture 에서 단 건 조회 시 22년도 데이터는 post 요청에서 에러가 뜨는 것을 해결하기 위해 커밋했습니다.
<br/>
<br/>
<br/>
> ♻️ 코드 수정: 강의 22년도 데이터도 전체 데이터에 포함되도록 수정

- src/components/marketing/CampaignFilter.vue
- src/views/marketing/campaign/AllCampaignsGetPage.vue
- 제목 : feat(#225 ): 캠페인 컬럼 정렬
<br/>
- 캠페인 전체 조회 화면에서 컬럼별로 정렬할 수 있게 했습니다.
<br/>
<br/>
- css 수정
<br/>
> ✨기능 추가: 캠페인 컬럼 정렬

- src/views/coupon/CouponView.vue
- src/views/coupon/IssuedCouponView.vue
<br/>
✨기능 추가: 쿠폰, 발급쿠폰 css 수정
<br/>
> ✨기능 추가: 쿠폰, 발급쿠폰 css 수정

- src/assets/css/member/StudentView.css
- src/assets/css/member/TutorView.css
- src/components/client/clientlogin/ClientLoginLeft.vue
- src/components/marketing/CampaignFilter.vue
- src/components/member/StudentCategoryRatioModal.vue
- src/views/MainView.vue
- src/views/marketing/campaign/AllCampaignsGetPage.vue
- src/views/marketing/campaignTemplate/AllCampaignTemplatesGetPage.vue
- src/views/member/StudentView.vue
- src/views/member/TutorView.vue
- 제목 : feat(#167 ):  StudentView 상세조회 css 수정
<br/>
- 학생 상세 조회, 강사 상세 조회 패널 크기 조절, css 통일, 메인페이지 로딩 지연 줄읾, 캠페인 컬럼 hover 추가
<br/>
<br/>
<br/>
> ♻️코드 수정: StudentView 상세조회 css 수정

- src/components/marketing/CouponDetail.vue
- src/components/voc/VocAiModal.vue
- src/views/coupon/CouponView.vue
<br/>
active_state로 돼 있는 부분을 couponFlag로 수정했습니다. 필터링, 삭제 시 매핑하는데 문제가 있어 수정했습니다.
> ♻️ 코드 수정: 쿠폰 삭제 시 전달 데이터 수정

- src/assets/css/member/ReservedBlacklistView.css
- src/components/AppHeader.vue
- src/components/marketing/TargetUserSelectModal.vue
- src/components/marketing/TimeSelect.vue
- src/views/marketing/campaign/CampaignGetPage.vue
- src/views/marketing/campaign/CampaignRegisterPage.vue
- src/views/member/ReservedBlacklistView.vue
- 제목 : feat(#167 ): ReservedBlacklistView css 수정
<br/>
- ReservedBlacklistView 상세조회 css 수정했습니다.
<br/>
<br/>
- 전체적인 css 수정
<br/>
> ♻️코드 수정: ReservedBlacklistView css 수정

- src/components/marketing/CouponDetail.vue
- src/views/coupon/CouponView.vue
<br/>
쿠폰 단 건 조회 시에 삭제 부분에 색도 같이 넣기 위해 css 수정했습니다.
<br/>
> 코드 수정: 쿠폰 단 건 조회 삭제처리 추가

- src/views/MainView.vue
- 제목 : feat(issue 번호): 기능명
ex) feat(17): pull request template 작성
(확인 후 지워주세요)
<br/>
✨기능 추가/수정: 메인뷰 전년도 대비 수익 그래프 수정
<br/>
> ✨기능 추가/수정: 메인뷰 전년도 대비 수익 그래프 수정

- src/components/marketing/CouponDetail.vue
쿠폰 단 건 조회 시 css가 올바르지 않게 돼 있어 수정했습니다.
> 쿠폰 단 건 조회 css 수정

- src/components/marketing/CouponDetail.vue
<br/>
쿠폰 단 건 조회 삭제 관련 css 수정
<br/>
> ♻️ 코드 수정: 쿠폰 단 건 조회 삭제 관련 css 수정

- src/assets/css/member/StudentView.css
> ✨기능 추가/수정: 학생 css 수정

- src/components/voc/VOCCustomCalendar.vue
- src/components/voc/VocAiModal.vue
- src/views/marketing/campaign/CampaignGetPage.vue
- 제목 : feat(#101 ): CampaignGetPage 수정
<br/>
- 캠페인 단건 조회 할 때 담당자가 로그인 한 유저의 이름으로 나타나는 오류가 있어 수정했습니다.
<br/>
<br/>
- 전체적인 css 수정
<br/>
> ♻️코드 수정: CampaignGetPage 수정

- src/views/marketing/campaign/CampaignGetPage.vue
- 제목 : feat(#100 ): campaignGetPage 날짜 오류 수정
<br/>
- 타겟 유저 생일 형식 오류로 캠페인 수정이 안되는 오류가 있어 수정했습니다.
<br/>
<br/>
- 오류 수정
<br/>
> ♻️코드 수정: campaignGetPage 날짜 오류 수정

- src/components/marketing/CampaignCouponSelectFilter.vue
- src/components/marketing/CampaignTemplateGetModal.vue
- 제목 : feat(#240 ): CampaignTemplateGetModal 수정
<br/>
- 캠페인 템플릿 수정 후 바로 수정사항이 업데이트 되지 않는 것을 고쳤습니다.
<br/>
<br/>
- 전체적인 오류 수정
<br/>
> ♻️코드 수정: CampaignTemplateGetModal 수정

- src/assets/css/member/BlacklistView.css
- src/assets/css/member/StudentView.css
- src/views/coupon/CouponView.vue
- src/views/coupon/IssuedCouponView.vue
<br/>
✨기능 추가/수정: 쿠폰, 발급쿠폰 마스킹처리, 발급쿠폰, 쿠폰, 고객, 블랙리스트 css 수정
<br/>
> ✨기능 추가/수정: 쿠폰, 발급쿠폰 마스킹처리, 발급쿠폰, 쿠폰, 고객, 블랙리스트 css 수정

- src/views/marketing/campaign/AllCampaignsGetPage.vue
- 제목 : feat(#84 ):캠페인 필터링 조회 오류 수정
<br/>
- 캠페인 필터링 적용 시 캠페인 타입이 한국어로 format이 안되어서 수정했습니다.
<br/>
<br/>
- css 수정
<br/>
> ♻️코드 수정: 캠페인 필터링 조회 오류 수정

- src/views/coupon/CouponRegisterView.vue
- 제목 : feat(#245 #246 )
<br/>
✨기능 추가/수정: 쿠폰 등록시 전체 강의 선택시 선택 안되던 오류 수정
<br/>
> ✨기능 추가/수정: 쿠폰 등록시 전체 강의 선택시 선택 안되던 오류 수정

- src/views/marketing/campaign/CampaignRegisterPage.vue
- 제목 : feat(issue 번호): 기능명
ex) feat(17): pull request template 작성
(확인 후 지워주세요)
<br/>
<br/>
<br/>
<br/>
> ♻️코드 수정: 캠페인 예약 수정

- src/views/coupon/CouponView.vue
- src/views/coupon/IssuedCouponView.vue
- 제목 : feat(#250 )
<br/>
필터링 api 호출 후 mask_name 추가 안해서 안보이는 오류 발생. 수정
<br/>
> ♻️코드 수정: 쿠폰 필터링 기능 추가 후 마스킹 처리 추가

- src/components/login/LoginPwLeft.vue
> ♻️ 코드 수정: 배포를 위해 커밋

- src/components/voc/VocAiModal.vue
- 제목 : feat(#254 )
<br/>
voc ai 모달에서 created 부분을 한국 시간대로 강제 설정했습니다.
<br/>
> ♻코드 수정: voc ai 모듈 클릭시 처음 뜨는 날짜 데이터 한국 timezone에 맞게 수정
